# Generated by Django 3.1.3 on 2021-02-09 22:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('descripcion', models.TextField(max_length=250)),
                ('detalle', models.TextField(max_length=500)),
                ('genero', models.CharField(default='INDEFINIDO', max_length=60)),
                ('clasificacion', models.CharField(choices=[('SINC', 'Sin clasificar'), ('ATP', 'ATP'), ('PLUS13', '+13'), ('PLUS16', '+16'), ('PLUS18', '+18')], default='SINC', max_length=8)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activa'), ('INACTIVO', 'Inactivo')], default='INACTIVO', max_length=8)),
                ('fechaComienzo', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaFinalizacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('HABILITADA', 'Habilitada'), ('DESHABILITADA', 'Deshabilitada'), ('ELIMINADA', 'Eliminada')], default='HABILITADA', max_length=13)),
                ('filas', models.PositiveSmallIntegerField()),
                ('asientos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(default='2019-01-01')),
                ('fechaFin', models.DateField(default='2020-01-01')),
                ('hora_proyeccion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Butaca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField()),
                ('fila', models.PositiveSmallIntegerField()),
                ('asiento', models.PositiveSmallIntegerField()),
                ('proyeccion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consultas.proyeccion')),
            ],
        ),
    ]
