# Generated by Django 3.1.3 on 2021-02-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='clasificacion',
            field=models.CharField(default='SINC', max_length=100),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='detalle',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='estado',
            field=models.CharField(default='INACTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(default='INDEFINIDO', max_length=100),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
