# Generated by Django 3.1.3 on 2020-11-17 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_proyeccion_sala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyeccion',
            old_name='sala',
            new_name='sala_id',
        ),
        migrations.AddField(
            model_name='proyeccion',
            name='pelicula_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consultas.pelicula'),
        ),
    ]
