# Generated by Django 3.1.3 on 2021-02-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_auto_20210209_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='estado',
            field=models.CharField(default='ACTIVA', max_length=10),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='fechaFin',
            field=models.DateField(default='01-01-2020'),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='fechaInicio',
            field=models.DateField(default='01-01-2020'),
        ),
    ]
