# Generated by Django 3.1.3 on 2021-02-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_auto_20210224_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='estado',
            field=models.CharField(choices=[('HABILITADA', 'Habilitada'), ('DESHABILITADA', 'Deshabilitada')], default='HABILITADA', max_length=13),
        ),
    ]
