# Generated by Django 3.1.3 on 2021-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_auto_20210224_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('INACTIVA', 'INACTIVA')], default='ACTIVA', max_length=10),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=8),
        ),
        migrations.AlterField(
            model_name='sala',
            name='estado',
            field=models.CharField(choices=[('HABILITADA', 'HABILITADA'), ('DESHABILITADA', 'DESHABILITADA')], default='HABILITADA', max_length=13),
        ),
    ]
